spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tejas@123
    username: root
    url: jdbc:mysql://localhost:3306/tejapatil
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
